### ISSUE TITLE
Lib-wrapper detects conflict with PF2

### ISSUE THREAD

**Issue by apoapostolov** [kandashi/Border-Control#1]
Reported via notification. I haven't noticed what actually breaks, but this mod is must-have for me for the border thickness alone, so please resolve this conflict. 

![image](https://user-images.githubusercontent.com/4083812/116166297-5f925500-a706-11eb-82d1-64ee0a3eb6e6.png)

**Comment by kandashi** [comment]
Both methods are applying the same patch, placing Border Control above PF2e will work fine
