### ISSUE TITLE
Bug: token border doesn't respect "scale" of token.

### ISSUE THREAD

**Issue by Merudo** [kandashi/Border-Control#21]
The token border doesn't respect the scale of the token.

If the token is made smaller by reducing the scale, the border will be much larger than the token.

![image](https://user-images.githubusercontent.com/7371085/117557283-e31d4180-b036-11eb-94a3-eee00760074d.png)

If the token is made larger by increasing the scale, the border will become invisible.

![image](https://user-images.githubusercontent.com/7371085/117557303-fe884c80-b036-11eb-9a70-6ace84cb4661.png)

**Comment by kandashi** [comment]
This is how the core system handles borders/scaling. I dont believe Im going to be changing this as it would interfere with many other situations
