### ISSUE TITLE
0.8.6. Border Width not working

### ISSUE THREAD

**Issue by apoapostolov** [kandashi/Border-Control#27]
Even if Border width is increased from 4 to 8, for example, it still looks the same under 0.8.6. Used to work in 0.7.10. 

In addition, HP Gradient feature is completely broken and no borders appear while it is activated.

**Comment by kandashi** [comment]
Both work fine in 0.8.6 with dnd 1.3.3 with only Border Control active for me.  Please test with no other modules enabed
