### ISSUE TITLE
Request Compatibility with Old-School Essentials

### ISSUE THREAD

**Issue by justinthejaguar** [kandashi/Border-Control#30]
Whenever I used Border Control in OSE, it appears to remove the border, but not replace it with anything else. Error pops.

![image](https://user-images.githubusercontent.com/38022481/121273278-e6a22380-c895-11eb-9cba-bedbb07ef2ae.png)

Foundry VTT Version 0.8.6

**Comment by kandashi** [comment]
(caused by HP gradient option which is only compatible with dnd5e)
