### ISSUE TITLE
Critical issue - players constantly get grey screen until scene changes 

### ISSUE THREAD

**Issue by apoapostolov** [kandashi/Border-Control#35]
Foundry 0.8.8 (but confirmed also 0.8.7), Border Control 1.2.04 - tested on clean Foundry no mods (+ libwrapper, via Culprit)

DM sees everything perfectly. Players have major issues:
* When world loads players see grey world. When the scene changes to another, they see it right, and when the scene returns to the previous, they see it right. Players complain from crashes, and players complain the screen goes gray (being players, they cannot tell what really happens) at irregular moments and they cannot catch what really makes it go gray. 
* Players report tokens disappearing, all tokens including enemies. When this happens, drawings disappear as well.

**Comment by kandashi** [comment]
Sorry this took a while to get to, fixed in next release
