### ISSUE TITLE
Minor bug with Perfect Vision

### ISSUE THREAD

**Issue by Ikabodo** [kandashi/Border-Control#37]
**Describe the bug**
After using find the culprit I managed to figure out that there is a minor compatibility issue with Perfect Vision. The issue is that If both modules are activated the border shows up on top of the token instead of under it. 

**To Reproduce**
1. Activate Border Control with dependencies
2. Activate Perfect Vision
3. Hover over token

**Expected behavior**
The border should appear under the token instead of above.

**Screenshots**
With Perfect Vision
![image](https://user-images.githubusercontent.com/7766890/127859736-43fa0516-ec61-4585-989f-2cb6f847a43f.png)

Without Perfect Vision
![image](https://user-images.githubusercontent.com/7766890/127859909-36fdd5d3-9682-4af9-aab7-b79951e872bb.png)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome and Firefox
 - Foundry Version 0.8.8
 - Module Version 1.2.05
 - All Modules Disabled: Yes
 - Module List if no: libWrapper dependency still active

**Additional context**
I did try managing the priorities in libWrapper, but it made no difference.

**Comment by Ikabodo** [comment]
https://github.com/dev7355608/perfect-vision/issues/103

**Comment by dev7355608** [comment]
This needs to be fixed by PV. I'm on it.
