### ISSUE TITLE
Conflict with Smart Target

### ISSUE THREAD

**Issue by Djahal** [kandashi/Border-Control#38]
**Describe the bug**
There's a conflict with the module Smart Target

**To Reproduce**
1. Just activate both modules and load a world or refresh.

**Expected behavior**
LibWrapper sreaming !

**Screenshots**
![image](https://user-images.githubusercontent.com/80932931/129439204-e3cb16cd-d14e-47e2-8d44-d786a3286756.png)
![image](https://user-images.githubusercontent.com/80932931/129439307-89a9208a-dd4e-4cc7-b247-a53dcd712ef6.png)

**Environment:**
 - OS: [Windows]
 - Browser : [Chrome]
 - Foundry Version [0.8.8]
 - Module Version [1.2.05]
 - All Modules Disabled: No

**Comment by kandashi** [comment]
See #15 and #31 
There is an option in Border Control to stop the targeting
