### ISSUE TITLE
Make the HP gradient attribute configurable or hide HP settings for unsupported systems

### ISSUE THREAD

**Issue by mkahvi** [kandashi/Border-Control#41]
**Is your feature request related to a problem? Please describe.**
HP gradient is shown for unsupported systems.

**Describe the solution you'd like**
Make the attribute configurable.
e.g. allow just typing in `data.status.wounds` or something and derive `.value` and `.max` from that. Though honestly the initial `data.` requirement shouldn't be there since no system can store their health outside of it.

**Describe alternatives you've considered**
Don't register the HP gradient settings on unsupported systems.

**Comment by kandashi** [comment]
Hidden for unsupported systems
