### ISSUE TITLE
Clarify units in settings

### ISSUE THREAD

**Issue by mkahvi** [kandashi/Border-Control#42]
**Is your feature request related to a problem? Please describe.**
The various sizes, offsets, widths, etc. don't say what units they are or what they relate to.

For example I entered 5 in an nameplate offset not knowing what it expected, and it seemed to do nothing.

**Describe the solution you'd like**
Better documentation.

**Describe alternatives you've considered**
Sadness.

**Comment by kandashi** [comment]
Added in 1.3
