### ISSUE TITLE
Settings preview

### ISSUE THREAD

**Issue by mkahvi** [kandashi/Border-Control#43]
**Is your feature request related to a problem? Please describe.**
Getting things right requires refreshing repeatedly and re-entering the module settings. Worse if you have more than one module enabled and need to find it among the million other settings in there.

**Describe the solution you'd like**
A simple-ish dialog with the current settings and a preview of what they'll lead up to.

**Describe alternatives you've considered**
Refreshing a lot.

**Comment by kandashi** [comment]
Im afraid I dont have the time/skill to do this.
