### ISSUE TITLE
Request: Persistent Token Borders

### ISSUE THREAD

**Issue by LonePaladin** [kandashi/Border-Control#44]
**Is your feature request related to a problem? Please describe.**
By default, tokens show a border when the user holds their mouse pointer over them. When you're using a shared display -- say, on a TV placed before a live group -- they typically don't have a mouse pointer so the token borders don't appear to them.

**Describe the solution you'd like**
This module could use an option to make token borders persistent. This would help users easily ID the disposition of an actor (i.e., Friendly or Hostile), and if they are using top-down tokens it can also help them quickly identify WHICH things are tokens. The visibility of a token's border would still be overridden by the option you've included of turning the border off. (That way your mimics stay hidden.)

**Describe alternatives you've considered**
I mean, sure, you can go into a token's art file and manually add a border around it. But if you're using a catalog of top-down tokens someone else has made, you don't want to have to go in there and give each one a ring, especially when what you want to show is already there in the system.

**Additional context**
Obviously, this would have to be an option to check on or off. Not everyone is going to want a constantly-visible box or ring around every token.

**Comment by kandashi** [comment]
Added in 1.3
