### ISSUE TITLE
Suggestion: An option to scale the border size to match token scale

### ISSUE THREAD

**Issue by silvative** [kandashi/Border-Control#45]
With your module I adjusted the border to be flush with my token ring, and have it showing the HP estimate on mouseover, which I absolutely love. 

![image](https://user-images.githubusercontent.com/66365038/140591051-e73b4005-87f8-4099-b07b-2cab3ecf2ddb.png)

However, tokens that are scaled (most frequently small creatures which are set to 0.8 scale) do not keep a flush border, leaving a gap. 

![image](https://user-images.githubusercontent.com/66365038/140591060-14d33e58-f69f-43b5-b642-fd552609c999.png)

I can just stop scaling small creatures down, but I was wondering if it'd be possible to make it so that the border would also scale down with the token in those cases?

**Comment by kandashi** [comment]
Added in 1.3
