### ISSUE TITLE
Scale border radius with grid-size

### ISSUE THREAD

**Issue by Ikabodo** [kandashi/Border-Control#46]
**Is your feature request related to a problem? Please describe.**
Borders are inconsistent over several scenes if the grid size is different. 

**Describe the solution you'd like**
Love the scaling option. Is there a way to scale borders to scene scale too?

**Describe alternatives you've considered**
It's possible to just keep the grid the same, but that is not always possible. Especially for patreon maps. 

**Additional context**
Grid-size: 100
![image](https://user-images.githubusercontent.com/7766890/141201527-f8306bbc-ac7e-4b03-91ce-6b4cbb38a892.png)

Grid-size: 256 (to show difference clearly)
![image](https://user-images.githubusercontent.com/7766890/141201539-e39a1bb7-e450-40a5-a658-f03b70014151.png)

**Comment by kandashi** [comment]
Ill give it a go, but it is deffinatly possible to just re-scale a scene

**Comment by kandashi** [comment]
Closed in lastest release
