### ISSUE TITLE
SFRPG compatability

### ISSUE THREAD

**Issue by C4M3R0N808** [kandashi/Border-Control#47]
This is a really cool module!

I was wondering if you had considered adding support for game systems like Starfinder?
If you're not familiar, the system uses a pool of stamina points (SP) before you go into your HP. So basically it would be like most systems seem to allow temp HP except it would roll another layer of SP in between the regular HP and temp HP. So basically my question is could you support 3 bars? Specifically **HP > SP > Temp HP** in the case of SFRPG.

Thanks!
Cameron

**Comment by kandashi** [comment]
I dont actually do anything to-do with the display of the health bars, only the token borders

**Comment by C4M3R0N808** [comment]
I said bars but I just meant 3 pools, sorry about that. Basically, could the border be made to support a 3rd pool and effectively add another layer to it?

**Comment by kandashi** [comment]
Im afraid I dont have the time to add in specific support, I would accept Pull Requests however
