### ISSUE TITLE
[Request] Option to force token labels to fit within token space

### ISSUE THREAD

**Issue by LonePaladin** [kandashi/Border-Control#48]
I like using the curved text with round tokens, it gives a nice consistent look. I had to do some tweaking to the settings to get the text to go up high enough to mesh with the tokens, though. And I've encountered a problem -- any token with a long text label shows this: the text is following a different curve than the outside of the token.

![image](https://user-images.githubusercontent.com/37523352/141606551-b913573e-7b71-4646-a715-54ef1dccf0b6.png)

I'd like a simple option to force the bottom curve of the text to conform to the size of its token, and to stay within a set proportion of that arc. Say, the bottom 1/3rd of it, a 60° arc. Make the text get narrower as needed to fit within that arc, or simply cut off the label if it's too long.

**Comment by kandashi** [comment]
It seems like you want to adjust the Circular Template Radius option

**Comment by LonePaladin** [comment]
> It seems like you want to adjust the Circular Template Radius option

Yes. Is it possible to constrain this text already? I couldn't find a combination of settings that made the bottom of the text follow the outer edge of the token, while also staying in the lower third (or even the lower half).

**Comment by kandashi** [comment]
There is no constraint of text size no.
