### ISSUE TITLE
[Suggestion] Actor Health as a reference to color the borders?

### ISSUE THREAD

**Issue by Jyhnu** [kandashi/Border-Control#5]
**Hello,**

I was wondering if it could be possible to use the token health as a reference to color the borders. This would be very useful to show which actor is hurt and how much, on a scale (from green to red, or customizable) when using round tokens instead of top-down ones.

**Example below:**

![image](https://user-images.githubusercontent.com/47944305/116402802-1ee12b80-a82d-11eb-96dc-87e07f57544a.png)

_Thank you again for your work, it's been amazing._

**Comment by kandashi** [comment]
Ooooh, i **LIKE** that idea
