### ISSUE TITLE
Border Control: OSE Error

### ISSUE THREAD

**Issue by justinthejaguar** [kandashi/Border-Control#55]
**Describe the bug**
Errors populate when you create a token.

**To Reproduce**
1. Create a world instance using Old-School Essentials System
2. Activate Border Control
3. Create Scene and Actor 
4. Drag Actor into 
5. See warning in console: 'game.data.version is deprecated since V9 in favor of game.version'

**Expected behavior**
Errors do not populate console. Uncertain of impact.

**Screenshots**
![Screen Shot 2022-01-15 at 4 39 22 PM](https://user-images.githubusercontent.com/38022481/149638553-82421ebb-12de-4976-b48b-1d04a678a4d2.png)

**Environment:**
 - OS: Mac M1
 - Browser chrome
 - Foundry Version 9 B242
 - Module Version 1.3.02
 - All Modules Disabled: No
 - Module List if no: libwrapper

**Additional context**

**Comment by kandashi** [comment]
Fixed in upcoming release
