### ISSUE TITLE
[HP gradient] Console Error resulting in the border not being drawn

### ISSUE THREAD

**Issue by Jyhnu** [kandashi/Border-Control#8]
**Hello again,**

That was fast! Thanks a lot!

While testing the new HP gradient feature, one of my player tokens sent this error in the console :

![image](https://user-images.githubusercontent.com/47944305/116689836-dbb3c380-a9b8-11eb-8030-5c36798c6c0c.png)

The token does not render a border and becomes very laggy to select.
However, when I deactivate the HP gradient feature, everything works fine again.

_On a side note : could it be possible to override the HP gradient if the token has Temp. HP (rendering the border in a defined color?)_

**Comment by kandashi** [comment]
what were the colors and step value used for the gradient?

#9 will follow the second suggestion

**Comment by Jyhnu** [comment]
I don't think I changed those settings. Here is a screenshot with my parameters:

![image](https://user-images.githubusercontent.com/47944305/116780339-601b4a80-aa7c-11eb-9cb3-4c24ef2ab663.png)

**Comment by kandashi** [comment]
Hum, i cant seem to replicate this. If its repeatable, try with only Border Controll active. If its still happening send me a discord PM and I'll join your server to see whats up. I

**Comment by Jyhnu** [comment]
I tried by removing all modules but Border Control and libWrapper. This one actor token (top right) still does not render its border (same console error):
![image](https://user-images.githubusercontent.com/47944305/116810935-cff60780-ab46-11eb-8552-b6c28ba511db.png)

**Comment by kandashi** [comment]
What were the value and max fields for that tokens HP?

**Comment by Jyhnu** [comment]
There were 30/25 HP, 9 Temp HP, 5 Max HP. The 5 other tokens have similar values, it's seems odd to me. Sadly I'm not knowledgeable enough on Foundry to try and track down the cause of this error.

Screenshot:
![image](https://user-images.githubusercontent.com/47944305/116903282-77a13180-ac3c-11eb-8e99-df6dfdd36cec.png)

**Comment by kandashi** [comment]
Ahh, going over hp max messes with it
